[package]
name = "private_voting"
type = "contract"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.43.0", directory="noir-projects/aztec-nr/aztec" }